config/routes.rb
Rails.application.routes.draw do
  resources :gifs
  resources :tags
  devise_for :users, controllers:{omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gif.rb
class Gif < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: %i[twitter]
  has_one_attached :photo
  has_many :gifs

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name
      # user.username = auth.info.nickname
    end
  end

  def email_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :set_gif, only: %i[ show edit update destroy ]

  # GET /gifs or /gifs.json
  def index
    @gifs = Gif.all
  end

  # GET /gifs/1 or /gifs/1.json
  def show
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit
  end

  # POST /gifs or /gifs.json
  def create
    @gif = Gif.new(gif_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: "Gif was successfully created." }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1 or /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: "Gif was successfully updated." }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1 or /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: "Gif was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif
      @gif = Gif.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gif_params
      params.require(:gif).permit(:user_id, :image, :tag_list)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  	@gif = Gif.new
  	@termo = params[:pesquisa]
  	@gifs = Gif.tagged_with(["#{params[:pesquisa]}"])
  	@mostuseds = ActsAsTaggableOn::Tag.most_used(10)
  	@gifsall = Gif.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
  	@tags = ActsAsTaggableOn::Tag.all
  end

  def show
  	@tag = ActsAsTaggableOn::Tag.find(params[:id])
  	@gifs = Gif.tagged_with(@tag.name)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
    def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user, event: :authentication
            set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format? 
        else
            session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
            redirect_to new_user_registration_url
        end
    end

    def failure
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) ,class: 'badge badge-primary mr-2' %>

app/views/gifs/_form.html.erb
<%= simple_form_for(@gif) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gifs/edit.html.erb
<h1>Editing Gif</h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>

app/views/gifs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gifs</h1>

<div class="row">
  <% @gifs.each do |gif| %>
    <div class="col-md-3 mr-4">
      <div class="card" style="width: 18rem;">
        <%= cl_image_tag gif.image.key, crop: :fill %>
        <div class="card-body">
          <span class="text-muted">Tags:</span>
          <%= render gif.tags %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Gif', new_gif_path %>

app/views/gifs/new.html.erb
<h1>New Gif</h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Back', gifs_path %>

app/views/gifs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<div class="col-md-6 mr-4">
  <div class="card" style="width: 18rem;">
    <%= cl_image_tag @gif.image.key, crop: :fill %>
    <div class="card-body">
      <span class="text-muted">Tags:</span>
      <%= render @gif.tags %>
    </div>
  </div>
</div>
</p>

<%= link_to 'Edit', edit_gif_path(@gif) %> |
<%= link_to 'Back', gifs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gifchallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">Bem Vindo ao Projeto GifChallenge</h1>
  <% if current_user %>
  	<hr class="my-4">
	<%= simple_form_for(@gif) do |f| %>
	  <h4>Adicione seu Gif aqui</h4>
	  <%= f.input :image, as: :file %>
	  <label>Tags</label>
	  <%= f.text_field :tag_list, input_html: {value: f.object.tag_list.to_s}, class: "form-control" %>
	  <small id="emailHelp" class="form-text text-muted">utilize virgula para separar as Tags</small>
	  <%= f.button :submit, "Criar Gif", class: "btn btn-primary mt-2" %>
	<% end %>
	<% else %>
	<p class="lead">Faça Login para Upar os Gifs</p>
<% end %>
</div>

<div class="row">
	<% if @termo %>
		<div class="col-md-12">
			<h4>Resultados para <%= @termo %></h4>
		</div>
  		<% @gifs.each do |gif| %>
	    <div class="col-md-3">
	      <div class="card w-100" style="width: 18rem;">
	        <%= cl_image_tag gif.image.key, crop: :fill %>
	        <div class="card-body">
	          <span class="text-muted">Tags:</span>
	          <%= render gif.tags %>
	        </div>
	      </div>
	    </div>
  <% end %>
  <% else %>
  	<% @gifsall.each do |gif| %>
	    <div class="col-md-3">
	      <div class="card w-100" style="width: 18rem;">
	        <%= cl_image_tag gif.image.key, crop: :fill %>
	        <div class="card-body">
	          <span class="text-muted">Tags:</span>
	          <%= render gif.tags %>
	        </div>
	      </div>
    	</div>
  	<% end %>
  <% end %>

  <div class="col-md-12 mt-4">
  	<h4>Ranking de Tags</h4>
  	<ol>
  		<% @mostuseds.each do |tag| %>
  		<li><%= tag.name %></li>
  		<% end %>
  	</ol>
  </div>





</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.casadaeducacao.com.br/octopus/design/images/34/products/b/carrinhopoliplaccccc.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= form_tag(root_path, method: :get, class: "form-inline mr-5") %>
        <input class= "form-control" type="search" name="pesquisa" placeholder="digite sua busca">
        <button class="btn btn-outline-primary" type="submit">Pesquisa</button>
      </form>


      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= current_user.email %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://i.pinimg.com/originals/09/0a/ea/090aea0be7fa8331086ce7023350ef0a.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tags/show.html.erb
<h1> <%= @tag.name %> </h1>

<div class="row">
  <% @gifs.each do |gif| %>
    <div class="col-md-3 mr-4">
      <div class="card" style="width: 18rem;">
        <%= cl_image_tag gif.image.key, crop: :fill %>
        <div class="card-body">
          <span class="text-muted">Tags:</span>
          <%= render gif.tags %>
        </div>
      </div>
    </div>
  <% end %>
</div>